- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: "DevOps with AWS"
    DURATION: "140HRS"
    TRAINER: "Reddy"
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "course name is: {{ COURSE }}, Trainer is: {{ TRAINER }}"