- name: Demo on filters
  hosts: local
  connection: local
  vars: #String
    topics: linux, shell, terraform, ansible'
    # tags: #map/dictionaries 
    #   name: ansible
    #   project: roboshop
    #   component: catalogue
    tagsmap:  #map/dictionaries 
      name: ansible
      project: roboshop
      component: catalogue
    tagslist: [
        {
            "key": "name",
            "value": "ansible"
        },
        {
            "key": "project",
            "value": "roboshop"
        },
        {
            "key": "component",
            "value": "catalogue"
        }
    ]

  tasks:
  - name: greeting
    ansible.builtin.debug:
      msg: "Hi Reddy, {{ GREETING | default('Good morning') }}"

  - name: convert string to list
    ansible.builtin.debug:
      msg: "{{ topics | split(',') }}"

  # - name: convert map to list
  #   ansible.builtin.debug:
  #     msg: "{{ tags |   dict2items }}" # [WARNING]: Found variable using reserved name: tags "by using this reserved keyword it throws this warning"

  - name: convert map to list
    ansible.builtin.debug:
      msg: "{{ tagsmap | dict2items }}" 

  - name: convert list to map
    ansible.builtin.debug:
      msg: "{{ tagslist | items2dict }}"

  - name: read students yaml
    amsiblr.builtin.set_fact: #setting the variable
      student_yaml: "{{ lookup('file','students.yaml' ) | from_yaml }}"
      
  - name: convert YAML to JSON
    ansible.builtin.debug:
      msg: "{{ student_yaml | to_nice_json }}"
