- name: Demo on filters
  hosts: local
  connection: local
  vars: #String
    topics: linux, shell, terraform, ansible'
  tags: #map/dictionaries
    name: ansible
    project: roboshop
    component: catalogue
  tasks:
  - name: greeting
    ansible.builtin.debug:
      msg: "Hi Reddy, {{ GREETING | default('Good morning') }}"

  - name: convert string to list
    ansible.builtin.debug:
      msg: "{{ topics | split(',') }}"

  - name: convert map to list
    ansible.builtin.debug:
      msg: "{{ tags | dict2items }}"
  